- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Setup rba role
      delegate_to: localhost
      citrix_adm_rba_role:
        adm_ip: "{{ adm_ip }}"
        adm_user: "{{ adm_user }}"
        adm_pass: "{{ adm_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: playbook_test_role
        description: some description
        tenant_id: 77ce04ac-127d-424e-8022-8a9d3853388e
        policies: 
          - readonlypolicy
