- hosts: citrix_adm

  gather_facts: False

  collections:
    - citrix.adm

  tasks:
    - name: Login to citrix_adm
      delegate_to: localhost
      register: login_result
      citrix_adm_login:
        adm_ip: "{{ adm_ip }}"
        adm_user: "{{ adm_user }}"
        adm_pass: "{{ adm_pass }}"
        validate_certs: "{{ validate_certs }}"

    - name: Get ns instance
      delegate_to: localhost
      register: ns_facts
      citrix_adm_ns_facts:
        adm_ip: "{{ adm_ip }}"
        nitro_auth_token: "{{ login_result.session_id }}"
        validate_certs: "{{ validate_certs }}"

        ip_address: '{{ instance_ip }}'

    - name: Setup application
      delegate_to: localhost
      citrix_adm_application:
        adm_ip: "{{ adm_ip }}"
        nitro_auth_token: "{{ login_result.session_id }}"
        validate_certs: "{{ validate_certs }}"


        state: present

        check_create: true
        check_create_delay: 10

        poll_after_delete: true
        poll_delay: 10

        app_category: test_category
        name: test_application_01
        stylebook_params: "{{ stylebook_params_local | to_json }}"
      vars:
        stylebook_params_local:
          configpack_payload:
            parameters:
              ip: 192.199.19.1
              lb-alg: ROUNDROBIN
              name: integration_test_application
              svc-port: "80"
              svc-servers:
                - 192.199.19.3
            targets:
              - id: '{{ ns_facts.ns[0].id }}'
          name: basic-lb-config
          namespace: com.example.stylebooks
          version: "0.1"
