- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Get all tenants
      delegate_to: localhost
      register: tenant_facts
      citrix_adm_tenant_facts:
        adm_ip: "{{ adm_ip }}"
        adm_user: "{{ adm_user }}"
        adm_pass: "{{ adm_pass }}"
        validate_certs: "{{ validate_certs }}"

        name: Owner


    - name: Show return data
      debug:
        var: tenant_facts

