- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Setup managed device
      delegate_to: localhost
      citrix_adm_managed_device:
        adm_ip: "{{ adm_ip }}"
        adm_user: "{{ adm_user }}"
        adm_pass: "{{ adm_pass }}"
        validate_certs: no

        state: present

        ip_address: 10.222.74.141
        profile_name: nsroot
