- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  vars:
    stylebook_contents: "{{ lookup('file', 'stylebook_sample.yaml') }}"
  collections:
    - citrix.adm

  tasks:
    - name: login
      delegate_to: localhost
      register: login_result
      citrix_adm_login:
        adm_ip: "{{ adm_ip }}"
        adm_user: "{{ adm_user }}"
        adm_pass: "{{ adm_pass }}"


    - name: Setup stylebook
      delegate_to: localhost
      citrix_adm_stylebook:
        adm_ip: "{{ adm_ip }}"
        nitro_auth_token: "{{ login_result.session_id }}"

        state: present

        name: basic-lb-config
        namespace: com.example.stylebooks
        version: "0.1"

        source: "{{ stylebook_contents }}"
