
- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Login to adm
      delegate_to: localhost
      register: login_result
      citrix_adm_login:
        adm_ip: "{{ adm_ip }}"
        adm_user: "{{ adm_user }}"
        adm_pass: "{{ adm_pass }}"
        validate_certs: "{{ validate_certs }}"

    - name: poll instances
      delegate_to: localhost
      citrix_adm_poll_instances:
        adm_ip: "{{ adm_ip }}"
        validate_certs: "{{ validate_certs }}"
        nitro_auth_token: "{{ login_result.session_id }}"
