- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Get all ns
      delegate_to: localhost
      register: ns_facts
      citrix_adm_ns_facts:
        adm_ip: "{{ adm_ip }}"
        adm_user: "{{ adm_user }}"
        adm_pass: "{{ adm_pass }}"
        validate_certs: "{{ validate_certs }}"

        ipv4_address: 10.222.74.141

    - name: Show return data
      debug:
        msg: "{{ ns_facts.ns }}"

