- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Setup appfw policy
      delegate_to: localhost
      citrix_adm_rba_policy:
        adm_ip: "{{ adm_ip }}"
        adm_user: "{{ adm_user }}"
        adm_pass: "{{ adm_pass }}"
        validate_certs: no

        state: present

        name: test_policy
        description: test description

        # need to quote true value to parse it as string
        # otherwise comparison with remote state fails
        statement:
          - access_type: "true"
            operation_name: add
            parent_name: rba_policy
            resource_type: ns_gslbservice

          - access_type: "true"
            operation_name: get
            parent_name: rba_policy
            resource_type: si_safety_signature
        ui:
          - access_type: "true"
            display_name: ""
            name: ContentSwitching
            parent_name: rba_policy
          - access_type: "true"
            display_name: ""
            name: ApplicationsDashboard
            parent_name: rba_policy
