- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Setup mpsuser
      delegate_to: localhost
      citrix_adm_mpsgroup:
        adm_ip: "{{ adm_ip }}"
        adm_user: "{{ adm_user }}"
        adm_pass: "{{ adm_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: playbook_test_mpsgroup_2
        permission: read-only
        allow_application_only: true
        session_timeout: 10
        session_timeout_unit: Minutes
        description: some description
        assign_all_apps: true
        enable_session_timeout: true
        assign_all_devices: false
        role: admin
        roles: 
          - admin
        application_names: []
        standalone_instances_id: []
        select_individual_entity: true
        authscope_props: []
        apply_all_bound_entities: false
        assign_all_selected_device_apps: false
        bound_entity_selected: 0
        assign_all_autoscale_groups: true
        autoscale_groups_id: []
