- hosts: citrix_adc

  gather_facts: no
  collections:
    - citrix.adc

  tasks:

    - name: Setup local gslb site
      delegate_to: localhost
      citrix_adc_gslb_site:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        sitename: gslb-site-http
        siteipaddress: 192.168.1.4

    - name: Setup local gslb service
      delegate_to: localhost
      citrix_adc_gslb_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        servicename: gslb-service-http
        servicetype: HTTP
        port: 80
        ipaddress: 10.0.0.1
        sitename: gslb-site-http
        cip: disabled
        disabled: no
        monitor_bindings:
          - monitor_name: http
            weight: 2


