- hosts: citrix_adm_service

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Logout from ADM service
      delegate_to: localhost
      citrix_adm_logout:

        adm_ip: "adm.cloud.com"
        is_cloud: true

        nitro_auth_token: "{{ login_result.session_id }}"
