- name: Add resource when not existing
  delegate_to: localhost
  citrix_adc_nitro_request:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"

    nitro_protocol: "{{ nitro_protocol }}"
    validate_certs: "{{ validate_certs }}"

    operation: add

    resource: "{{ processed_role_input.resource }}"
    attributes: "{{ processed_role_input.resource_attributes }}"
