- hosts: citrix_adc
  gather_facts: no
  vars:
    resource: server
    attributes:
      name: test-server-1
      ipaddress: 192.168.1.6
  collections:
    - citrix.adc

  tasks:
    - name: Add resource with idempotent flag
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        operation: update
        name: test-server-1
        idempotent: yes

        resource: "{{ resource }}"
        attributes: "{{ attributes }}"
