- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - ../../deps/workflows.yaml
  collections:
    - citrix.adc

  tasks:
    - name: Add authentication epaaction
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_protocol: http
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        workflow: "{{ workflow.authentication_epaaction }}"

        resource:
          name: epa_act_ConfidentialMACs
          csecexpr: "sys.client_expr(\"app_0_MAC-BROWSER_1001_VERSION_<=_10.0.3\")"
          defaultepagroup: ConfidentialDevice
          quarantinegroup: NotConfidentialDevice
          #killprocess:
          #deletefiles: