- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - ../../deps/workflows.yaml
  collections:
    - citrix.adc

  tasks:
    - name: Setup server
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        workflow: "{{ workflow.server }}"

        resource:
          name: test-server
          ipaddress: 192.168.11.34

    - name: Disable server
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        operation: action
        action: disable

        resource: server
        attributes:
          name: test-server
          delay: 30
          graceful: !!str yes
