- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - ../../deps/workflows.yaml
  collections:
    - citrix.adc

  tasks:
    - name: Setup nitro resource
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        workflow: "{{ workflow.ntpserver }}"

        resource:
          serverip: 216.239.35.12
          minpoll: "5"
