- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - ../../deps/workflows.yaml
  collections:
    - citrix.adc

  tasks:
    - name: Setup nitro ntp parameters
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        workflow: "{{ workflow.ntpparam }}"

        resource:
          autokeylogsec: "12"
          revokelogsec: "16"
