- hosts: citrix_adc

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adc


  tasks:
    - name: Upload signatures file
      delegate_to: localhost
      citrix_adc_system_file:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        validate_certs: no

        state: present

        filename: Scan_Report_ctrx8pb_20200109.xml
        filelocation: /var/tmp
        filecontent: "{{ lookup('file', 'files/Scan_Report_ctrx8pb_20200109.xml') }}"

    - name: setup appfw signatures 
      delegate_to: localhost
      register: result
      citrix_adc_appfw_signatures_custom_import:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        validate_certs: no

        state: present 

        name: "scan_report_sig"
        src: "local:Scan_Report_ctrx8pb_20200109.xml"
        xslt_builtin: "Qualys_cloud_2_42_3"

        enable_all: true
        block_all: true
        log_all: true
        stats_all: false
