- hosts: citrix_adc

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adc


  tasks:
    - name: setup systemfile
      delegate_to: localhost
      citrix_adc_system_file:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        validate_certs: no

        state: present

        filename: system_file.yaml
        filelocation: /var/tmp
        filecontent: "{{ lookup('file', 'system_file.yaml') }}"

