- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Setup nsrec
      delegate_to: localhost
      citrix_adc_dnsnsrec:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        domain: hello.com
        nameserver: 10.3.3.4
        ttl: 1111
