---

- hosts: citrix_adc

  vars_files:
    - ../deps/workflows.yaml
  gather_facts: False
  collections: citrix.adc

  tasks:

    - name: Set soa record
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        nitro_protocol: https
        validate_certs: no

        state: absent

        workflow: "{{ workflow.dnssoarec }}"

        resource:
          domain: hello.com
          originserver: 10.2.3.5
          contact: other
          expire: 1600
