- hosts: citrix_adc

  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Setup cipher
      delegate_to: localhost
      citrix_adc_sslcipher:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no
        state: present

        ciphergroupname: test_cipher

    - name: Setup cipher binding
      delegate_to: localhost
      citrix_adc_sslcipher_sslciphersuite_binding:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no
        state: present

        ciphergroupname: test_cipher
        ciphername: TLS1.2-ECDHE-RSA-AES256-GCM-SHA384
        cipherpriority: "2"

    - name: Setup cipher binding
      delegate_to: localhost
      citrix_adc_sslcipher_sslciphersuite_binding:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no
        state: present

        ciphergroupname: test_cipher
        ciphername: SSL3-EXP-ADH-DES-CBC-SHA
        cipherpriority: "4"

