- hosts: citrix_adc

  vars:
    max_clients: 5
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Setup binding
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        validate_certs: no

        operation: delete_by_args
        resource: sslvserver_sslcipher_binding
        args:
          ciphername: DEFAULT
          vservername: test_ssl
