- hosts: citrix_adc

  vars:
    max_clients: 5
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Retrieve info
      delegate_to: localhost
      citrix_adc_nitro_info:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        endpoint: interface
        args:
          id: LO/1
        nitro_info_key: Interface

      register: result

    - name: Show nitro_info
      debug:
        msg: "nitro_info {{ result['nitro_info'] }}"

    - name: Get sslparameters
      delegate_to: localhost
      citrix_adc_nitro_info:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        validate_certs: no

        endpoint: sslparameter

      register: result

    - name: Show nitro_info
      debug:
        msg: "nitro_info {{ result['nitro_info'] }}"
