- name: Delete resource
  delegate_to: localhost
  register: result
  citrix_adc_nitro_request:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"

    nitro_protocol: "{{ nitro_protocol }}"
    validate_certs: "{{ validate_certs }}"

    operation: delete_by_args

    resource: "{{ processed_role_input.resource }}/{{ processed_role_input.resource_name }}"
    args: "{{ delete_args }}"
