---
- hosts: citrix_adc

  gather_facts: False
  collections:
    - citrix.adc

  tasks:

    - name: Setup service
      delegate_to: localhost
      citrix_adc_nsip:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        ipaddress: 192.168.2.2
        netmask: 255.255.255.0
        type: VIP
        snmp: disabled
        disabled: no
