---
- hosts: citrix_adc

  gather_facts: False
  collections:
    - citrix.adc

  tasks:

    - name: Setup partition
      delegate_to: localhost
      citrix_adc_nspartition:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        partitionname: par1
        maxbandwidth: 10240
