---
- hosts: citrix_adc

  gather_facts: False
  collections:
    - citrix.adc

  tasks:

    - name: ADC login
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        validate_certs: "{{ validate_certs }}"

        operation: add

        resource: "login"
        attributes:
          username: "{{ nitro_user }}"
          password: "{{ nitro_pass }}"

    - name: Extract login data from http response
      set_fact:
        login_data: "{{ result.http_response_body | from_json }}"

    - name: Setup partition and switch
      delegate_to: localhost
      citrix_adc_nspartition:
        nsip: "{{ nsip }}"
        nitro_auth_token: "{{ login_data.sessionid }}"
        validate_certs: no

        state: present

        partitionname: par1
        maxbandwidth: 10240
        switch_partition: yes

    - name: setup lb vserver on partition
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ nsip }}"
        nitro_auth_token: "{{ login_data.sessionid }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: lb-vserver-1
        servicetype: HTTP
        ipv46: 6.93.3.3
        port: 80
        disabled: no
