- hosts: citrix_adc
  gather_facts: no

  tasks:

    - name: 'Create binding'
      import_role:
        name: adc_resource_binding_create
      vars:
        role_input:
          resource: lbgroup_lbvserver_binding
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          id_attributes:
            - vservername
          resource_attributes:
            name: integration_test_lbgroup1
            vservername: integration_test_lbvserver1

    - name: 'Delete binding'
      import_role:
        name: adc_resource_binding_delete
      vars:
        role_input:
          resource: lbgroup_lbvserver_binding
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          id_attributes:
            - vservername
          resource_attributes:
            name: integration_test_lbgroup1
            vservername: integration_test_lbvserver1
