- hosts: citrix_adc
  gather_facts: no
  tasks:

    - name: 'Delete idempotency'
      import_role:
        name: adc_resource_delete
      vars:
        role_input:
          resource: lbgroup
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          resource_non_updateable_attributes:
            - newname
          resource_attributes:
            name: integration_test_lbgroup1
            persistencetype: SOURCEIP

    - name: 'Assert delete operation was none'
      assert:
        that:
          - 'role_output.operation == "none"'

    - name: 'Create resource dry run'
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbgroup
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          resource_non_updateable_attributes:
            - newname
          resource_attributes:
            name: integration_test_lbgroup1
            persistencetype: SOURCEIP
          dry_run: true

    - name: 'Assert create dry run'
      assert:
        that:
          - 'role_output.operation == "create"'

    - name: 'Create resource dry run'
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbgroup
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          resource_non_updateable_attributes:
            - newname
          resource_attributes:
            name: integration_test_lbgroup1
            persistencetype: SOURCEIP

    - name: 'Assert create'
      assert:
        that:
          - 'role_output.operation == "create"'

    - name: 'Create resource dry run'
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbgroup
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          resource_non_updateable_attributes:
            - newname
          resource_attributes:
            name: integration_test_lbgroup1
            persistencetype: NONE
          dry_run: true

    - name: 'Assert update'
      assert:
        that:
          - 'role_output.operation == "update"'

    - name: 'Create resource dry run'
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbgroup
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          resource_non_updateable_attributes:
            - newname
          resource_attributes:
            name: integration_test_lbgroup1
            persistencetype: NONE

    - name: 'Assert update'
      assert:
        that:
          - 'role_output.operation == "update"'

    - name: 'Create resource dry run'
      import_role:
        name: adc_resource_delete
      vars:
        role_input:
          resource: lbgroup
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          resource_non_updateable_attributes:
            - newname
          resource_attributes:
            name: integration_test_lbgroup1
            persistencetype: NONE
          dry_run: true

    - name: 'Assert create'
      assert:
        that:
          - 'role_output.operation == "delete"'

    - name: 'Create resource dry run'
      import_role:
        name: adc_resource_delete
      vars:
        role_input:
          resource: lbgroup
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          resource_non_updateable_attributes:
            - newname
          resource_attributes:
            name: integration_test_lbgroup1
            persistencetype: NONE

    - name: 'Assert create'
      assert:
        that:
          - 'role_output.operation == "delete"'
