- hosts: citrix_adc
  gather_facts: no

  tasks:

    - name: 'Create resource'
      import_role:
        name: adc_resource_create_or_update
      vars:
        debug_prefix: lbgroup_
        resource: lbgroup
        resource_name: integration_test_lbgroup1
        resource_missing_errorcode:
          - 258
        resource_non_updateable_attributes:
          - newname
        resource_attributes:
          name: integration_test_lbgroup1
          persistencetype: SOURCEIP

    - name: 'Delete resource'
      import_role:
        name: adc_resource_delete
      vars:
        debug_prefix: lbgroup_
        resource: lbgroup
        resource_name: integration_test_lbgroup1
        resource_missing_errorcode:
          - 258
