- hosts: citrix_adc
  gather_facts: no
  tasks:

    - name: 'Create dependency'
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbvserver
          resource_attributes:
            ipv46: 12.23.53.31
            name: integration_test_lbvserver1
            port: 80
            servicetype: HTTP
          resource_missing_errorcode:
            - 258
          resource_name: integration_test_lbvserver1

    - name: 'Create dependency'
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbvserver
          resource_attributes:
            ipv46: 12.23.53.32
            name: integration_test_lbvserver2
            port: 80
            servicetype: HTTP
          resource_missing_errorcode:
            - 258
          resource_name: integration_test_lbvserver2

    - name: 'Create dependency'
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbgroup
          resource_attributes:
            name: integration_test_lbgroup1
            persistencetype: SOURCEIP
          resource_missing_errorcode:
            - 258
          resource_name: integration_test_lbgroup1
          resource_non_updateable_attributes:
            - newname

    - name: 'Create binding dry run'
      import_role:
        name: adc_resource_binding_create
      vars:
        role_input:
          resource: lbgroup_lbvserver_binding
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          id_attributes:
            - vservername
          resource_attributes:
            name: integration_test_lbgroup1
            vservername: integration_test_lbvserver1
          dry_run: true

    - name: 'Assert create'
      assert:
        that:
          - 'role_output.operation == "create"'

    - name: 'Create binding dry run'
      import_role:
        name: adc_resource_binding_create
      vars:
        role_input:
          resource: lbgroup_lbvserver_binding
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          id_attributes:
            - vservername
          resource_attributes:
            name: integration_test_lbgroup1
            vservername: integration_test_lbvserver1

    - name: 'Assert create'
      assert:
        that:
          - 'role_output.operation == "create"'

    - name: 'Delete binding dry run'
      import_role:
        name: adc_resource_binding_delete
      vars:
        role_input:
          resource: lbgroup_lbvserver_binding
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          id_attributes:
            - vservername
          resource_attributes:
            name: integration_test_lbgroup1
            vservername: integration_test_lbvserver1
          dry_run: true

    - name: 'Assert delete'
      assert:
        that:
          - 'role_output.operation == "delete"'

    - name: 'Delete binding'
      import_role:
        name: adc_resource_binding_delete
      vars:
        role_input:
          resource: lbgroup_lbvserver_binding
          resource_name: integration_test_lbgroup1
          resource_missing_errorcode:
            - 258
          id_attributes:
            - vservername
          resource_attributes:
            name: integration_test_lbgroup1
            vservername: integration_test_lbvserver1

    - name: 'Assert delete'
      assert:
        that:
          - 'role_output.operation == "delete"'

    - name: 'Delete dependency'
      import_role:
        name: adc_resource_delete
      vars:
        role_input:
          resource: lbgroup
          resource_attributes:
            name: integration_test_lbgroup1
            persistencetype: SOURCEIP
          resource_missing_errorcode:
            - 258
          resource_name: integration_test_lbgroup1
          resource_non_updateable_attributes:
            - newname

    - name: 'Delete dependency'
      import_role:
        name: adc_resource_delete
      vars:
        role_input:
          resource: lbvserver
          resource_attributes:
            ipv46: 12.23.53.32
            name: integration_test_lbvserver2
            port: 80
            servicetype: HTTP
          resource_missing_errorcode:
            - 258
          resource_name: integration_test_lbvserver2

    - name: 'Delete dependency'
      import_role:
        name: adc_resource_delete
      vars:
        role_input:
          resource: lbvserver
          resource_attributes:
            ipv46: 12.23.53.31
            name: integration_test_lbvserver1
            port: 80
            servicetype: HTTP
          resource_missing_errorcode:
            - 258
          resource_name: integration_test_lbvserver1
