- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:

    - name: Login to adm
      delegate_to: localhost
      register: login_result
      citrix_adm_login:
        adm_ip: "{{ adm_ip }}"
        adm_user: test_user
        adm_pass: welcome

    - name: Setup domain name
      delegate_to: localhost
      citrix_adm_dns_domain_entry:
        adm_ip: "{{ adm_ip }}"
        nitro_auth_token: "{{ login_result.session_id }}"

        state: present

        name: app1.acme.com
        description: some description

    - name: Get ns instance
      delegate_to: localhost
      register: ns_facts
      citrix_adm_ns_facts:
        adm_ip: "{{ adm_ip }}"
        nitro_auth_token: "{{ login_result.session_id }}"

        ip_address: 10.78.60.209

    - name: Set facts
      set_fact:
        stylebook_facts:
          name: "basic-lb-config"
          namespace: "com.example.stylebooks"
          version: "0.1"
          configpack_payload:
            parameters:
              name: "test_application_6"
              ip: "192.169.10.2"
              lb-alg: "ROUNDROBIN"
              svc-servers:
                - "192.169.10.3"
              svc-port: "80"
            targets:
              - id: "{{ ns_facts.ns[0].id }}"


    - name: Setup application
      delegate_to: localhost
      citrix_adm_application:
        adm_ip: "{{ adm_ip }}"
        nitro_auth_token: "{{ login_result.session_id }}"

        state: present

        app_category: test_category
        name: test_application_6
        stylebook_params: "{{ stylebook_facts | to_json }}"
